groups:
  - name: alert.rules
    rules:
      - alert: InstanceDown
#        https://groups.google.com/g/prometheus-users/c/i-jOoQYI_mk
        expr: probe_success{instance="192.168.165.96:8685"} == 0
        for: 10s
        labels:
          severity: "critical"
        annotations:
          summary: "Endpoint {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
