groups:
  - name: alert.rules
    rules:
      - alert: external_service_not_reachable
        expr: probe_success{instance="192.168.165.96:8685"} == 0
        for: 1m
        labels:
          type: alert
          severity: "critical"
        annotations:
          summary: "Endpoint {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
