global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: https
    tls_config:
      ca_file: /home/prometheus/tls/prometheus.crt
    static_configs:
      - targets:
          - prometheus.gov:9090


  # if adding other group, add [job_name] section like follows
  # any name is OK for [job_name]
  - job_name: backend
    metrics_path: /q/metrics
    static_configs:
      - targets: ['backend.gov:8585']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor.gov:8080']

  - job_name: node-exporter
    scheme: https
    metrics_path: /metrics
    tls_config:
      ca_file: /home/prometheus/tls/node-exporter.crt
    static_configs:
      - targets: ['node-exporter.gov:9100']

  - job_name: blackbox
    metrics_path: /probe
    scheme: https
    tls_config:
      ca_file: /home/prometheus/tls/blackbox.crt
    params:
      module: [ tcp_connect ]
    static_configs:
      - targets:
          - 192.168.165.96:8685
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox.gov:9115