services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--web.external-url=https://prometheus/'
    ports:
      - 9090:9090
    restart: unless-stopped
    extra_hosts:
      - "asghar: 192.168.165.96"
    volumes:
      - ./tls/prometheus:/home/prometheus/certs
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
#    networks:
#      - ${GLOBAL_NETWORK}

  blackbox:
    image: bitnami/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - 9115:9115
    extra_hosts:
      - "asghar: 192.168.165.96"
    command:
      - '--config.file=/config/blackbox.yml'
      - '--web.config.file=/config/web-config.yml'
    volumes:
      - ./blackbox:/config
      - ./tls/blackbox:/home/blackbox/certs

#    networks:
#      - ${GLOBAL_NETWORK}

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=khesam109
      - GF_SECURITY_ADMIN_PASSWORD=salamsalam
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/home/grafana/certs/grafana.crt
      - GF_SERVER_CERT_KEY=/home/grafana/certs/grafana.key
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/blackbox-exporter.json

    volumes:
#      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
#      - ./grafana/config/test:/etc/apk/repositories
#      - ./grafana/config/grafana.ini:/etc/grafana/asghar/grafana.ini
      - ./tls/grafana:/home/grafana/certs
#    networks:
#      - ${GLOBAL_NETWORK}

  backend:
    image: com.khesam/monitoring:2.0.0
    container_name: test_monitoring
    ports:
      - 8585:8585
#    networks:
#      - ${GLOBAL_NETWORK}

volumes:
  prom_data:

#networks:
#  kc_net:
#    external: true
#    name: test-monitoring