version: '3.9'
services:
  alert-manager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager.gov
    environment:
      - TZ=Iran
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--web.external-url=http://alertmanager.gov:9093'
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/etc/alertmanager