version: '3.7'
services:
  blackbox:
    image: bitnami/blackbox-exporter:latest
    container_name: blackbox-exporter
    hostname: blackbox.gov
    ports:
      - "9115:9115"
    command:
      - '--config.file=/config/blackbox.yml'
      - '--web.config.file=/config/web-config.yml'
    volumes:
      - ./blackbox:/config
      - ./tls/blackbox:/home/blackbox/certs