version: '3.9'
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor.gov
    ports:
      - "9101:9101"
    privileged: true
    command:
      - '-port=9101'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
#    networks:
#      - ${GLOBAL_NETWORK}