version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    hostname: prometheus.gov
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--web.external-url=https://prometheus.gov/'
    ports:
      - "9090:9090"
    restart: unless-stopped
#    extra_hosts:
#      - "node-exporter.gov:192.169.165.96"
    volumes:
      - ./tls/prometheus:/home/prometheus/tls
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
#    networks:
#      - ${GLOBAL_NETWORK}
volumes:
  prom_data: