version: '3.9'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    hostname: prometheus.gov
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--web.external-url=https://prometheus.gov/'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./tls/prometheus:/home/prometheus/tls
      - ./prometheus:/etc/prometheus
      - ./storage/prometheus-storage:/prometheus
volumes:
  prom_data: