global:
  resolve_timeout: 5m
templates:
  - '/etc/alertmanager/*.tmpl'
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 15s
  repeat_interval: 30s
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
#    https://prometheus.io/docs/alerting/latest/configuration/#http_config
    webhook_configs:
      - url: 'http://192.168.165.96:8585/alert-manager/webhook'
        send_resolved: true